Life of 3.14159: Drone.DroneController.AutoPilot.ThinkingState Class Reference
Drone.DroneController.AutoPilot.ThinkingState Class Reference
Public Member Functions
void adjustAction (AutoPilot autopilot)
String toString ()
Static Private Attributes
static final float accuracy = AutoPilot.ERROR
Detailed Description
This is the default state for the autopilot to go to, it decided which state needs to be transitioned too in order to complete the task.
Author
orpheus
Definition at line 8 of file ThinkingState.java.
Member Function Documentation
void Drone.DroneController.AutoPilot.ThinkingState.adjustAction (AutoPilot autopilot)
chose an appropriate state to transition too by comparing the target X,Y,Z coordinates to the drones current X,Y,Z, coordinates.
Exceptions
Exception
check to see if the drones X-location is (within error bounds) matches the target X-location
check to see if the drones Y-location is (within error bounds) matches the target Y-location
check to see if the drones Z-location is (within error bounds) matches the target Z-location
Implements Drone.DroneController.AutoPilot.AutoPilotState.
Definition at line 19 of file ThinkingState.java.
References Drone.DroneController.AutoPilot.ThinkingState.accuracy, Drone.DroneController.AutoPilot.AutoPilotState.adjustAction(), Drone.DroneController.Location.getX(), Drone.DroneController.Location.getY(), Drone.DroneController.Location.getZ(), Drone.DroneController.AutoPilot.AutoPilot.location, Drone.DroneController.AutoPilot.AutoPilot.setState(), Drone.DroneController.AutoPilot.AutoPilot.state, Drone.DroneController.AutoPilot.AutoPilot.xTarget, Drone.DroneController.AutoPilot.AutoPilot.yTarget, and Drone.DroneController.AutoPilot.AutoPilot.zTarget.
     {
         if (autopilot.location.getX() >= (autopilot.xTarget+accuracy) ||
             autopilot.location.getX() <= (autopilot.xTarget-accuracy))
         {
             autopilot.setState(new AdjustXState());
             System.out.println("adjust x");
             autopilot.state.adjustAction(autopilot);
         }
         else if (autopilot.location.getY() >= (autopilot.yTarget+accuracy) ||
                 autopilot.location.getY() <= (autopilot.yTarget-accuracy))
         {
             autopilot.setState(new AdjustYState());
             System.out.println("adjust y");
             autopilot.state.adjustAction(autopilot);
         }
         else if (autopilot.location.getZ() >= (autopilot.zTarget+accuracy) ||
                 autopilot.location.getZ() <= (autopilot.zTarget-accuracy))
         {
             autopilot.setState(new AdjustZState());
             System.out.println("adjust z");
             autopilot.state.adjustAction(autopilot);
         }
         else
         {
             System.out.println("Target Reached");
         }
     }
String Drone.DroneController.AutoPilot.ThinkingState.toString ()
return a string label with the state
Returns
"Thinking...."
Implements Drone.DroneController.AutoPilot.AutoPilotState.
Definition at line 66 of file ThinkingState.java.
     {
         return "Thinking.....";
     }
Member Data Documentation
final float Drone.DroneController.AutoPilot.ThinkingState.accuracy = AutoPilot.ERROR static private
accuracy(Error) of adjustments
Definition at line 11 of file ThinkingState.java.
Referenced by Drone.DroneController.AutoPilot.ThinkingState.adjustAction().
The documentation for this class was generated from the following file:
ThinkingState.java