Life of 3.14159: workspace.ARDroneNavData.src.controller.DroneTest Class Reference
workspace.ARDroneNavData.src.controller.DroneTest Class Reference
Public Member Functions
Mode getMode ()
int getSequence ()
boolean isControlReceived ()
FlyingState getFlyingState ()
Static Public Member Functions
static void qqmain (String args[]) throws Exception
static void qmain (String args[]) throws Exception
static void main (String args[]) throws Exception
static void qqqmain (String args[]) throws Exception
static float getAltitude ()
static int getBattery ()
static ControlAlgorithm getControlAlgorithm ()
static CtrlState getControlState ()
static float getLongitude ()
static float getPitch ()
static float getRoll ()
static float getVx ()
static float getVz ()
static float getYaw ()
static boolean isAcquisitionThreadOn ()
static boolean isADCWatchdogDelayed ()
static boolean isAltitudeControlActive ()
static boolean isAngelsOutOufRange ()
static boolean isATCodedThreadOn ()
static boolean isBatteryTooHigh ()
static boolean isBatteryTooLow ()
static boolean isCommunicationProblemOccurred ()
static boolean isControlWatchdogDelayed ()
static boolean isCutoutSystemDetected ()
static boolean isEmergency ()
static boolean isFlying ()
static boolean isGyrometersDown ()
static boolean isMotorsDown ()
static boolean isNavDataBootstrap ()
static boolean isNavDataDemoOnly ()
static boolean isNavDataThreadOn ()
static boolean isNotEnoughPower ()
static boolean isPICVersionNumberOK ()
static boolean isTimerElapsed ()
static boolean isTooMuchWind ()
static boolean isTrimReceived ()
static boolean isTrimRunning ()
static boolean isTrimSucceeded ()
static boolean isUltrasonicSensorDeaf ()
static boolean isUserFeedbackOn ()
static boolean isVideoEnabled ()
static boolean isVideoThreadOn ()
static boolean isVisionEnabled ()
static List< VisionTag > getVisionTags ()
static void setVisionTags (List< VisionTag > vt)
static void createFromData (ByteBuffer buf, int len)
static void printState ()
static void send_at_cmd (String at_cmd) throws Exception
Static Protected Attributes
static Mode mode
static boolean flying
static boolean videoEnabled
static boolean visionEnabled
static ControlAlgorithm controlAlgorithm
static boolean altitudeControlActive
static boolean userFeedbackOn
static boolean controlReceived
static boolean trimReceived
static boolean trimRunning
static boolean trimSucceeded
static boolean navDataDemoOnly
static boolean navDataBootstrap
static boolean motorsDown
static boolean gyrometersDown
static boolean batteryTooLow
static boolean batteryTooHigh
static boolean timerElapsed
static boolean notEnoughPower
static boolean angelsOutOufRange
static boolean tooMuchWind
static boolean ultrasonicSensorDeaf
static boolean cutoutSystemDetected
static boolean PICVersionNumberOK
static boolean ATCodedThreadOn
static boolean navDataThreadOn
static boolean videoThreadOn
static boolean acquisitionThreadOn
static boolean controlWatchdogDelayed
static boolean ADCWatchdogDelayed
static boolean communicationProblemOccurred
static boolean emergency
static int sequence
static CtrlState ctrl_state
static int battery
static float altitude
static float pitch
static float roll
static float yaw
static float vx
static float vy
static float vz
static List< VisionTag > vision_tags
Static Private Member Functions
static String GetNDField (int i)
static List< VisionTag > parseVisionTags (ByteBuffer buf, int offset)
static void parseDemoNavData (ByteBuffer buf, int offset)
static void parseState (int state)
Static Private Attributes
static InetAddress inet_addr = null
static DatagramSocket atsocket = null
static DatagramSocket ndsocket = null
Detailed Description
Definition at line 12 of file DroneTest.java.
Member Function Documentation
static void workspace.ARDroneNavData.src.controller.DroneTest.createFromData (ByteBuffer buf, int len) static
Definition at line 449 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.Mode.BOOTSTRAP, workspace.ARDroneNavData.src.controller.Mode.DEMO, workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_CKS_TAG, workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_DEMO_TAG, workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_VISION_DETECT_TAG, workspace.ARDroneNavData.src.controller.DroneTest.parseDemoNavData(), workspace.ARDroneNavData.src.controller.DroneTest.parseState(), workspace.ARDroneNavData.src.controller.DroneTest.parseVisionTags(), workspace.ARDroneNavData.src.controller.DroneTest.printState(), and workspace.ARDroneNavData.src.controller.DroneTest.setVisionTags().
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.qqqmain().
     {
         if (ByteOrder.LITTLE_ENDIAN != buf.order()) {
             buf.order(ByteOrder.LITTLE_ENDIAN);
         }
         mode = Mode.BOOTSTRAP; // Assume we are in bootstrap
         //int offset = 0;
         int header = buf.getInt(0);
         if(header != 0x55667788)
         {
             System.out.println("Error parsing NavData");
             System.exit(1);
         }
        // offset += 4;
         int state = buf.getInt(4);
         //offset += 4;
         parseState(state);
         sequence = buf.getInt(8);
         //offset += 4;
         int vision_flag = buf.getInt(12);
         System.out.println(vision_flag);
         //offset += 4;
         printState();
         //System.exit(1);
         int offset = 16;
         // Read options
         System.out.println(buf.get(offset));
         System.out.println(buf.get(offset+1));
         System.out.println(buf.get(offset+2));
         System.out.println(buf.get(offset+3));
         while(offset < len)
         {
             int option_tag = buf.getShort(offset);
             offset += 2;
             int option_len = buf.getShort(offset);
             offset += 2;
             if(option_len == 0)
             {
                 System.out.println("Zero-len option with tag " + option_tag);
                 //System.exit(1);
                 return;
             }
             // log.fine("At offset " + (offset - 4) + " found option " +
             // option_tag + " with len=" + option_len);
             if(option_tag == NavDataTag.NAVDATA_DEMO_TAG.getValue())
             {
                 parseDemoNavData(buf, offset);
                 mode = Mode.DEMO;
             } else if(option_tag == NavDataTag.NAVDATA_CKS_TAG.getValue())
             {
                 // this is last tag. We do not unpack it yet, but we gracefully
                 // exit if it has been encountered.
                 break;
             } else if(option_tag == NavDataTag.NAVDATA_VISION_DETECT_TAG.getValue())
             {
                 List<VisionTag> vtags = parseVisionTags(buf, offset);
                 if(vtags != null)
                     setVisionTags(vtags);
             } else
             {
                 //log.warning("Skipping unknown NavData option with tag=" + option_tag);
             }
             offset = offset + option_len - 4;
         }
     }
static float workspace.ARDroneNavData.src.controller.DroneTest.getAltitude () static
Definition at line 224 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.altitude.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return altitude;
     }
static int workspace.ARDroneNavData.src.controller.DroneTest.getBattery () static
Definition at line 229 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.battery.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return battery;
     }
static ControlAlgorithm workspace.ARDroneNavData.src.controller.DroneTest.getControlAlgorithm () static
Definition at line 234 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.controlAlgorithm.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return controlAlgorithm;
     }
static CtrlState workspace.ARDroneNavData.src.controller.DroneTest.getControlState () static
Definition at line 239 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.ctrl_state.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return ctrl_state;
     }
FlyingState workspace.ARDroneNavData.src.controller.DroneTest.getFlyingState ()
Definition at line 434 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.FlyingState.fromControlState().
     {
         return FlyingState.fromControlState(ctrl_state);
     }
static float workspace.ARDroneNavData.src.controller.DroneTest.getLongitude () static
Definition at line 244 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.vy.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return vy;
     }
Mode workspace.ARDroneNavData.src.controller.DroneTest.getMode ()
Definition at line 249 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.mode.
     {
         return mode;
     }
static String workspace.ARDroneNavData.src.controller.DroneTest.GetNDField (int i) static private
Definition at line 145 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.qqqmain().
     {
         String fn = "";
         if (i == 0) fn = "Header";
         if (i == 1) fn = "Header";
         if (i == 2) fn = "Header";
         if (i == 3) fn = "Header";
         if (i == 4) fn = "State";
         if (i == 5) fn = "State";
         if (i == 6) fn = "State";
         if (i == 7) fn = "State";
         if (i == 8) fn = "SN";
         if (i == 9) fn = "SN";
         if (i == 10) fn = "SN";
         if (i == 11) fn = "SN";
         if (i == 12) fn = "VF";
         if (i == 13) fn = "VF";
         if (i == 14) fn = "VF";
         if (i == 15) fn = "VF";
         if (i == 16) fn = "Option";
         if (i == 17) fn = "Option";
         if (i == 18) fn = "Size";
         if (i == 19) fn = "Size";
         return(fn);
     }
static float workspace.ARDroneNavData.src.controller.DroneTest.getPitch () static
Definition at line 254 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.pitch.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return pitch;
     }
static float workspace.ARDroneNavData.src.controller.DroneTest.getRoll () static
Definition at line 259 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.roll.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return roll;
     }
int workspace.ARDroneNavData.src.controller.DroneTest.getSequence ()
Definition at line 264 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.sequence.
     {
         return sequence;
     }
static List<VisionTag> workspace.ARDroneNavData.src.controller.DroneTest.getVisionTags () static
Definition at line 439 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.vision_tags.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return vision_tags;
     }
static float workspace.ARDroneNavData.src.controller.DroneTest.getVx () static
Definition at line 269 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.vx.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return vx;
     }
static float workspace.ARDroneNavData.src.controller.DroneTest.getVz () static
Definition at line 274 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.vz.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return vz;
     }
static float workspace.ARDroneNavData.src.controller.DroneTest.getYaw () static
Definition at line 279 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.yaw.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return yaw;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isAcquisitionThreadOn () static
Definition at line 284 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.acquisitionThreadOn.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return acquisitionThreadOn;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isADCWatchdogDelayed () static
Definition at line 289 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.ADCWatchdogDelayed.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return ADCWatchdogDelayed;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isAltitudeControlActive () static
Definition at line 294 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.altitudeControlActive.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return altitudeControlActive;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isAngelsOutOufRange () static
Definition at line 299 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.angelsOutOufRange.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return angelsOutOufRange;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isATCodedThreadOn () static
Definition at line 304 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.ATCodedThreadOn.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return ATCodedThreadOn;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isBatteryTooHigh () static
Definition at line 309 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.batteryTooHigh.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return batteryTooHigh;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isBatteryTooLow () static
Definition at line 314 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.batteryTooLow.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return batteryTooLow;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isCommunicationProblemOccurred () static
Definition at line 319 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.communicationProblemOccurred.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return communicationProblemOccurred;
     }
boolean workspace.ARDroneNavData.src.controller.DroneTest.isControlReceived ()
Definition at line 324 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.controlReceived.
     {
         return controlReceived;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isControlWatchdogDelayed () static
Definition at line 329 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.controlWatchdogDelayed.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return controlWatchdogDelayed;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isCutoutSystemDetected () static
Definition at line 334 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.cutoutSystemDetected.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return cutoutSystemDetected;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isEmergency () static
Definition at line 339 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.emergency.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return emergency;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isFlying () static
Definition at line 344 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.flying.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return flying;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isGyrometersDown () static
Definition at line 349 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.gyrometersDown.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return gyrometersDown;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isMotorsDown () static
Definition at line 354 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.motorsDown.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return motorsDown;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isNavDataBootstrap () static
Definition at line 359 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.navDataBootstrap.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return navDataBootstrap;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isNavDataDemoOnly () static
Definition at line 364 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.navDataDemoOnly.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return navDataDemoOnly;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isNavDataThreadOn () static
Definition at line 369 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.navDataThreadOn.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return navDataThreadOn;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isNotEnoughPower () static
Definition at line 374 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.notEnoughPower.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return notEnoughPower;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isPICVersionNumberOK () static
Definition at line 379 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.PICVersionNumberOK.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return PICVersionNumberOK;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isTimerElapsed () static
Definition at line 384 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.timerElapsed.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return timerElapsed;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isTooMuchWind () static
Definition at line 389 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.tooMuchWind.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return tooMuchWind;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isTrimReceived () static
Definition at line 394 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.trimReceived.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return trimReceived;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isTrimRunning () static
Definition at line 399 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.trimRunning.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return trimRunning;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isTrimSucceeded () static
Definition at line 404 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.trimSucceeded.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return trimSucceeded;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isUltrasonicSensorDeaf () static
Definition at line 409 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.ultrasonicSensorDeaf.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return ultrasonicSensorDeaf;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isUserFeedbackOn () static
Definition at line 414 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.userFeedbackOn.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return userFeedbackOn;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isVideoEnabled () static
Definition at line 419 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.videoEnabled.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return videoEnabled;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isVideoThreadOn () static
Definition at line 424 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.videoThreadOn.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return videoThreadOn;
     }
static boolean workspace.ARDroneNavData.src.controller.DroneTest.isVisionEnabled () static
Definition at line 429 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.visionEnabled.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.printState().
     {
         return visionEnabled;
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.main (String args[]) throws Exception static
Definition at line 45 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.send_at_cmd().
     {
         int seq = 0;
         byte[] ip_bytes = new byte[4];
         ip_bytes[0] = (byte)192;
         ip_bytes[1] = (byte)168;
         ip_bytes[2] = (byte)1;
         ip_bytes[3] = (byte)1;
         inet_addr = InetAddress.getByAddress(ip_bytes);
         atsocket = new DatagramSocket();
         ndsocket = new DatagramSocket();
         atsocket.setSoTimeout(3000);
         ndsocket.setSoTimeout(3000);
         send_at_cmd("AT*CONFIG=1,\"control:altitude_max\",\"2000\"");
         String action = "Takeoff";
         String at_cmd = "AT*REF=" + (seq++) + ",290718208";
         send_at_cmd(at_cmd);
         Thread.sleep(15000);
         action = "Landing";
         at_cmd = "AT*REF=" + (seq++) + ",290717696";
         send_at_cmd(at_cmd);
         atsocket.close();
         ndsocket.close();
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.parseDemoNavData (ByteBuffer buf, int offset) static private
Definition at line 553 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.CtrlState.fromInt().
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
     {
         ctrl_state = CtrlState.fromInt(buf.getInt(offset) >> 16);
         offset += 4;
         battery = buf.getInt(offset);
         offset += 4;
         pitch = buf.getFloat(offset) / 1000;
         offset += 4;
         roll = buf.getFloat(offset) / 1000;
         offset += 4;
         yaw = buf.getFloat(offset) / 1000;
         offset += 4;
         altitude = ((float) buf.getInt(offset)) / 1000;
         offset += 4;
         vx = buf.getFloat(offset);
         offset += 4;
         vy = buf.getFloat(offset);
         offset += 4;
         vz = buf.getFloat(offset);
         offset += 4;
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.parseState (int state) static private
Definition at line 575 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.ControlAlgorithm.ANGULAR_SPEED_CONTROL, and workspace.ARDroneNavData.src.controller.ControlAlgorithm.EULER_ANGELS_CONTROL.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
     {
         flying = (state & 1) != 0;
         videoEnabled = (state & (1 << 1)) != 0;
         visionEnabled = (state & (1 << 2)) != 0;
         controlAlgorithm = (state & (1 << 3)) != 0 ? ControlAlgorithm.ANGULAR_SPEED_CONTROL : ControlAlgorithm.EULER_ANGELS_CONTROL;
         altitudeControlActive = (state & (1 << 4)) != 0;
         userFeedbackOn = (state & (1 << 5)) != 0;
         controlReceived = (state & (1 << 6)) != 0;
         trimReceived = (state & (1 << 7)) != 0;
         trimRunning = (state & (1 << 8)) != 0;
         trimSucceeded = (state & (1 << 9)) != 0;
         navDataDemoOnly = (state & (1 << 10)) != 0;
         navDataBootstrap = (state & (1 << 11)) != 0;
         motorsDown = (state & (1 << 12)) != 0;
         //ARDRONE_COM_LOST_MASK       = 1U << 13, /*!< Communication Lost : (1) com problem, (0) Com is ok */
         gyrometersDown = (state & (1 << 14)) != 0;
         batteryTooLow = (state & (1 << 15)) != 0;
         batteryTooHigh = (state & (1 << 16)) != 0;
         timerElapsed = (state & (1 << 17)) != 0;
         notEnoughPower = (state & (1 << 18)) != 0;
         angelsOutOufRange = (state & (1 << 19)) != 0;
         tooMuchWind = (state & (1 << 20)) != 0;
         ultrasonicSensorDeaf = (state & (1 << 21)) != 0;
         cutoutSystemDetected = (state & (1 << 22)) != 0;
         PICVersionNumberOK = (state & (1 << 23)) != 0;
         ATCodedThreadOn = (state & (1 << 24)) != 0;
         navDataThreadOn = (state & (1 << 25)) != 0;
         videoThreadOn = (state & (1 << 26)) != 0;
         acquisitionThreadOn = (state & (1 << 27)) != 0;
         controlWatchdogDelayed = (state & (1 << 28)) != 0;
         ADCWatchdogDelayed = (state & (1 << 29)) != 0;
         communicationProblemOccurred = (state & (1 << 30)) != 0;
         emergency = (state & (1 << 31)) != 0;
     }
static List<VisionTag> workspace.ARDroneNavData.src.controller.DroneTest.parseVisionTags (ByteBuffer buf, int offset) static private
Definition at line 530 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
     {
         int nb_detected = buf.getInt(offset);
         offset += 4;
         assert (nb_detected > 0);
         List<VisionTag> res = new ArrayList<VisionTag>(nb_detected);
         for(int i = 0; i < nb_detected; i++)
         {
             int type = buf.getInt(offset + 4 * i);
             int xc = buf.getInt(offset + 4 * i + 1 * 4 * 4);
             int yc = buf.getInt(offset + 4 * i + 2 * 4 * 4);
             int width = buf.getInt(offset + 4 * i + 3 * 4 * 4);
             int height = buf.getInt(offset + 4 * i + 4 * 4 * 4);
             int dist = buf.getInt(offset + 4 * i + 5 * 4 * 4);
             VisionTag vt = new VisionTag(VisionTag.VisionTagType.fromInt(type), new Point(xc, yc), new Dimension(width, height),dist);
             res.add(vt);
         }
         return res;
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.printState () static
Definition at line 611 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.getAltitude(), workspace.ARDroneNavData.src.controller.DroneTest.getBattery(), workspace.ARDroneNavData.src.controller.DroneTest.getControlAlgorithm(), workspace.ARDroneNavData.src.controller.DroneTest.getControlState(), workspace.ARDroneNavData.src.controller.DroneTest.getLongitude(), workspace.ARDroneNavData.src.controller.DroneTest.getPitch(), workspace.ARDroneNavData.src.controller.DroneTest.getRoll(), workspace.ARDroneNavData.src.controller.DroneTest.getVisionTags(), workspace.ARDroneNavData.src.controller.DroneTest.getVx(), workspace.ARDroneNavData.src.controller.DroneTest.getVz(), workspace.ARDroneNavData.src.controller.DroneTest.getYaw(), workspace.ARDroneNavData.src.controller.DroneTest.isAcquisitionThreadOn(), workspace.ARDroneNavData.src.controller.DroneTest.isADCWatchdogDelayed(), workspace.ARDroneNavData.src.controller.DroneTest.isAltitudeControlActive(), workspace.ARDroneNavData.src.controller.DroneTest.isAngelsOutOufRange(), workspace.ARDroneNavData.src.controller.DroneTest.isATCodedThreadOn(), workspace.ARDroneNavData.src.controller.DroneTest.isBatteryTooHigh(), workspace.ARDroneNavData.src.controller.DroneTest.isBatteryTooLow(), workspace.ARDroneNavData.src.controller.DroneTest.isCommunicationProblemOccurred(), workspace.ARDroneNavData.src.controller.DroneTest.isControlWatchdogDelayed(), workspace.ARDroneNavData.src.controller.DroneTest.isCutoutSystemDetected(), workspace.ARDroneNavData.src.controller.DroneTest.isEmergency(), workspace.ARDroneNavData.src.controller.DroneTest.isFlying(), workspace.ARDroneNavData.src.controller.DroneTest.isGyrometersDown(), workspace.ARDroneNavData.src.controller.DroneTest.isMotorsDown(), workspace.ARDroneNavData.src.controller.DroneTest.isNavDataBootstrap(), workspace.ARDroneNavData.src.controller.DroneTest.isNavDataDemoOnly(), workspace.ARDroneNavData.src.controller.DroneTest.isNavDataThreadOn(), workspace.ARDroneNavData.src.controller.DroneTest.isNotEnoughPower(), workspace.ARDroneNavData.src.controller.DroneTest.isPICVersionNumberOK(), workspace.ARDroneNavData.src.controller.DroneTest.isTimerElapsed(), workspace.ARDroneNavData.src.controller.DroneTest.isTooMuchWind(), workspace.ARDroneNavData.src.controller.DroneTest.isTrimReceived(), workspace.ARDroneNavData.src.controller.DroneTest.isTrimRunning(), workspace.ARDroneNavData.src.controller.DroneTest.isTrimSucceeded(), workspace.ARDroneNavData.src.controller.DroneTest.isUltrasonicSensorDeaf(), workspace.ARDroneNavData.src.controller.DroneTest.isUserFeedbackOn(), workspace.ARDroneNavData.src.controller.DroneTest.isVideoEnabled(), workspace.ARDroneNavData.src.controller.DroneTest.isVideoThreadOn(), and workspace.ARDroneNavData.src.controller.DroneTest.isVisionEnabled().
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
     {
         StringBuffer sb = new StringBuffer();
         sb.append("IsFlying: " + isFlying() + "\n");
         sb.append("IsVideoEnabled: " + isVideoEnabled() + "\n");
         sb.append("IsVisionEnabled: " + isVisionEnabled() + "\n");
         sb.append("controlAlgo: " + getControlAlgorithm() + "\n");
         sb.append("AltitudeControlActive: " + isAltitudeControlActive() + "\n");
         sb.append("IsUserFeedbackOn: " + isUserFeedbackOn() + "\n");
         sb.append("ControlReceived: " + isVideoEnabled() + "\n");
         sb.append("IsTrimReceived: " + isTrimReceived() + "\n");
         sb.append("IsTrimRunning: " + isTrimRunning() + "\n");
         sb.append("IsTrimSucceeded: " + isTrimSucceeded() + "\n");
         sb.append("IsNavthisDemoOnly: " + isNavDataDemoOnly() + "\n");
         sb.append("IsNavthisBootstrap: " + isNavDataBootstrap() + "\n");
         sb.append("IsMotorsDown: " + isMotorsDown() + "\n");
         sb.append("IsGyrometersDown: " + isGyrometersDown() + "\n");
         sb.append("IsBatteryLow: " + isBatteryTooLow() + "\n");
         sb.append("IsBatteryHigh: " + isBatteryTooHigh() + "\n");
         sb.append("IsTimerElapsed: " + isTimerElapsed() + "\n");
         sb.append("isNotEnoughPower: " + isNotEnoughPower() + "\n");
         sb.append("isAngelsOutOufRange: " + isAngelsOutOufRange() + "\n");
         sb.append("isTooMuchWind: " + isTooMuchWind() + "\n");
         sb.append("isUltrasonicSensorDeaf: " + isUltrasonicSensorDeaf() + "\n");
         sb.append("isCutoutSystemDetected: " + isCutoutSystemDetected() + "\n");
         sb.append("isPICVersionNumberOK: " + isPICVersionNumberOK() + "\n");
         sb.append("isATCodedThreadOn: " + isATCodedThreadOn() + "\n");
         sb.append("isNavthisThreadOn: " + isNavDataThreadOn() + "\n");
         sb.append("isVideoThreadOn: " + isVideoThreadOn() + "\n");
         sb.append("isAcquisitionThreadOn: " + isAcquisitionThreadOn() + "\n");
         sb.append("isControlWatchdogDelayed: " + isControlWatchdogDelayed() + "\n");
         sb.append("isADCWatchdogDelayed: " + isADCWatchdogDelayed() + "\n");
         sb.append("isCommunicationProblemOccurred: " + isCommunicationProblemOccurred() + "\n");
         sb.append("IsEmergency: " + isEmergency() + "\n");
         sb.append("CtrlState: " + getControlState() + "\n");
         sb.append("Battery: " + getBattery() + "\n");
         sb.append("Altidtude: " + getAltitude() + "\n");
         sb.append("Pitch: " + getPitch() + "\n");
         sb.append("Roll: " + getRoll() + "\n");
         sb.append("Yaw: " + getYaw() + "\n");
         sb.append("X velocity: " + getVx() + "\n");
         sb.append("Y velocity: " + getLongitude() + "\n");
         sb.append("Z velocity: " + getVz() + "\n");
         sb.append("Vision Tags: " + getVisionTags() + "\n");
         System.out.println(sb);
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.qmain (String args[]) throws Exception static
Definition at line 28 of file DroneTest.java.
     {
         Socket sock = new Socket("192.168.1.1", 5559);
         System.out.println("Here 1");
         InputStream is = sock.getInputStream();
         System.out.println("Here 2");
         int read;
         byte[] buffer = new byte[1024];
         while((read = is.read(buffer)) != -1)
         {
             String output = new String(buffer, 0, read);
             System.out.print(output);
             System.out.flush();
         }
         sock.close();
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.qqmain (String args[]) throws Exception static
Definition at line 17 of file DroneTest.java.
     {
         ByteBuffer bb = ByteBuffer.allocate(4);
         bb.put((byte)0,(byte)255);
         bb.put((byte)1,(byte)255);
         bb.put((byte)2,(byte)8);
         bb.put((byte)3,(byte)0);
         System.out.println(bb.getShort(0));
         System.out.println(bb.getShort(2));
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.qqqmain (String args[]) throws Exception static
Definition at line 80 of file DroneTest.java.
References workspace.ARDroneNavData.src.controller.DroneTest.createFromData(), workspace.ARDroneNavData.src.controller.DroneTest.GetNDField(), and workspace.ARDroneNavData.src.controller.DroneTest.send_at_cmd().
     {
         byte[] ip_bytes = new byte[4];
         ip_bytes[0] = (byte)192;
         ip_bytes[1] = (byte)168;
         ip_bytes[2] = (byte)1;
         ip_bytes[3] = (byte)1;
         inet_addr = InetAddress.getByAddress(ip_bytes);
         atsocket = new DatagramSocket();
         ndsocket = new DatagramSocket();
         atsocket.setSoTimeout(3000);
         ndsocket.setSoTimeout(3000);
         byte[] buffer = new byte[1024];
         buffer[0] = 1;
         buffer[1] = 0;
         buffer[2] = 0;
         buffer[3] = 0;
         DatagramPacket packet = new DatagramPacket(buffer, buffer.length, inet_addr, 5554);
         ndsocket.send(packet);
         Thread.sleep(500);
         ndsocket.receive(packet);
         send_at_cmd("AT*CTRL=0");
         send_at_cmd("AT*CONFIG=605,\"general:navdata_demo\",\"FALSE\"");
         //send_at_cmd("AT*CTRL=0");
         ndsocket.receive(packet);
         ByteBuffer bb = ByteBuffer.allocate(buffer.length);
         bb.put(buffer);
         //send_at_cmd("AT*CONFIG=1,\"control:altitude_max\",\"2000\"",inet_addr,socket); //altitude max 2m
         //send_at_cmd("AT*CONFIG=\"general:navdata_demo\",\"TRUE\"",inet_addr);
         //send_at_cmd("AT*CTRL=0",inet_addr,socket);
         createFromData(bb,buffer.length);
         //send_at_cmd("AT*CTRL=0",inet_addr);
         //socket.receive(packet);
         //bb = ByteBuffer.allocate(buffer.length);
         //bb.put(buffer);
         //send_at_cmd("AT*CONFIG=1,\"control:altitude_max\",\"2000\"",inet_addr,socket); //altitude max 2m
         //send_at_cmd("AT*CONFIG=\"general:navdata_demo\",\"TRUE\"",inet_addr);
         //send_at_cmd("AT*CTRL=0",inet_addr,socket);
         //createFromData(bb,buffer.length);
         for(int i=0;i<1000;++i)
         {
             String x = String.format("%s %2x",GetNDField(i),buffer[i] & 255);
             System.out.println(x);
         }
         atsocket.close();
         ndsocket.close();
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.send_at_cmd (String at_cmd) throws Exception static
Definition at line 659 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.main(), and workspace.ARDroneNavData.src.controller.DroneTest.qqqmain().
     {
         System.out.println("AT command: " + at_cmd);
         byte[] buffer = (at_cmd + "\r").getBytes();
         DatagramPacket packet = new DatagramPacket(buffer, buffer.length, inet_addr, 5556);
         atsocket.send(packet);
         //sock.close();
         //socket.receive(packet); //AR.Drone does not send back ack message (like "OK")
         //System.out.println(new String(packet.getData(),0,packet.getLength()));
     }
static void workspace.ARDroneNavData.src.controller.DroneTest.setVisionTags (List< VisionTag > vt) static
Definition at line 444 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
     {
         vision_tags = vt;
     }
Member Data Documentation
boolean workspace.ARDroneNavData.src.controller.DroneTest.acquisitionThreadOn static protected
Definition at line 201 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isAcquisitionThreadOn().
boolean workspace.ARDroneNavData.src.controller.DroneTest.ADCWatchdogDelayed static protected
Definition at line 203 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isADCWatchdogDelayed().
float workspace.ARDroneNavData.src.controller.DroneTest.altitude static protected
Definition at line 213 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getAltitude().
boolean workspace.ARDroneNavData.src.controller.DroneTest.altitudeControlActive static protected
Definition at line 178 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isAltitudeControlActive().
boolean workspace.ARDroneNavData.src.controller.DroneTest.angelsOutOufRange static protected
Definition at line 193 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isAngelsOutOufRange().
boolean workspace.ARDroneNavData.src.controller.DroneTest.ATCodedThreadOn static protected
Definition at line 198 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isATCodedThreadOn().
DatagramSocket workspace.ARDroneNavData.src.controller.DroneTest.atsocket = null static private
Definition at line 15 of file DroneTest.java.
int workspace.ARDroneNavData.src.controller.DroneTest.battery static protected
Definition at line 212 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getBattery().
boolean workspace.ARDroneNavData.src.controller.DroneTest.batteryTooHigh static protected
Definition at line 190 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isBatteryTooHigh().
boolean workspace.ARDroneNavData.src.controller.DroneTest.batteryTooLow static protected
Definition at line 189 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isBatteryTooLow().
boolean workspace.ARDroneNavData.src.controller.DroneTest.communicationProblemOccurred static protected
Definition at line 204 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isCommunicationProblemOccurred().
ControlAlgorithm workspace.ARDroneNavData.src.controller.DroneTest.controlAlgorithm static protected
Definition at line 177 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getControlAlgorithm().
boolean workspace.ARDroneNavData.src.controller.DroneTest.controlReceived static protected
Definition at line 181 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isControlReceived().
boolean workspace.ARDroneNavData.src.controller.DroneTest.controlWatchdogDelayed static protected
Definition at line 202 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isControlWatchdogDelayed().
CtrlState workspace.ARDroneNavData.src.controller.DroneTest.ctrl_state static protected
Definition at line 211 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getControlState().
boolean workspace.ARDroneNavData.src.controller.DroneTest.cutoutSystemDetected static protected
Definition at line 196 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isCutoutSystemDetected().
boolean workspace.ARDroneNavData.src.controller.DroneTest.emergency static protected
Definition at line 205 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isEmergency().
boolean workspace.ARDroneNavData.src.controller.DroneTest.flying static protected
Definition at line 174 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isFlying().
boolean workspace.ARDroneNavData.src.controller.DroneTest.gyrometersDown static protected
Definition at line 188 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isGyrometersDown().
InetAddress workspace.ARDroneNavData.src.controller.DroneTest.inet_addr = null static private
Definition at line 14 of file DroneTest.java.
Mode workspace.ARDroneNavData.src.controller.DroneTest.mode static protected
Definition at line 171 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getMode().
boolean workspace.ARDroneNavData.src.controller.DroneTest.motorsDown static protected
Definition at line 187 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isMotorsDown().
boolean workspace.ARDroneNavData.src.controller.DroneTest.navDataBootstrap static protected
Definition at line 186 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isNavDataBootstrap().
boolean workspace.ARDroneNavData.src.controller.DroneTest.navDataDemoOnly static protected
Definition at line 185 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isNavDataDemoOnly().
boolean workspace.ARDroneNavData.src.controller.DroneTest.navDataThreadOn static protected
Definition at line 199 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isNavDataThreadOn().
DatagramSocket workspace.ARDroneNavData.src.controller.DroneTest.ndsocket = null static private
Definition at line 16 of file DroneTest.java.
boolean workspace.ARDroneNavData.src.controller.DroneTest.notEnoughPower static protected
Definition at line 192 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isNotEnoughPower().
boolean workspace.ARDroneNavData.src.controller.DroneTest.PICVersionNumberOK static protected
Definition at line 197 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isPICVersionNumberOK().
float workspace.ARDroneNavData.src.controller.DroneTest.pitch static protected
Definition at line 214 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getPitch().
float workspace.ARDroneNavData.src.controller.DroneTest.roll static protected
Definition at line 215 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getRoll().
int workspace.ARDroneNavData.src.controller.DroneTest.sequence static protected
Definition at line 208 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getSequence().
boolean workspace.ARDroneNavData.src.controller.DroneTest.timerElapsed static protected
Definition at line 191 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isTimerElapsed().
boolean workspace.ARDroneNavData.src.controller.DroneTest.tooMuchWind static protected
Definition at line 194 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isTooMuchWind().
boolean workspace.ARDroneNavData.src.controller.DroneTest.trimReceived static protected
Definition at line 182 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isTrimReceived().
boolean workspace.ARDroneNavData.src.controller.DroneTest.trimRunning static protected
Definition at line 183 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isTrimRunning().
boolean workspace.ARDroneNavData.src.controller.DroneTest.trimSucceeded static protected
Definition at line 184 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isTrimSucceeded().
boolean workspace.ARDroneNavData.src.controller.DroneTest.ultrasonicSensorDeaf static protected
Definition at line 195 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isUltrasonicSensorDeaf().
boolean workspace.ARDroneNavData.src.controller.DroneTest.userFeedbackOn static protected
Definition at line 179 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isUserFeedbackOn().
boolean workspace.ARDroneNavData.src.controller.DroneTest.videoEnabled static protected
Definition at line 175 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isVideoEnabled().
boolean workspace.ARDroneNavData.src.controller.DroneTest.videoThreadOn static protected
Definition at line 200 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isVideoThreadOn().
List<VisionTag> workspace.ARDroneNavData.src.controller.DroneTest.vision_tags static protected
Definition at line 222 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getVisionTags().
boolean workspace.ARDroneNavData.src.controller.DroneTest.visionEnabled static protected
Definition at line 176 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.isVisionEnabled().
float workspace.ARDroneNavData.src.controller.DroneTest.vx static protected
Definition at line 217 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getVx().
float workspace.ARDroneNavData.src.controller.DroneTest.vy static protected
Definition at line 218 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getLongitude().
float workspace.ARDroneNavData.src.controller.DroneTest.vz static protected
Definition at line 219 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getVz().
float workspace.ARDroneNavData.src.controller.DroneTest.yaw static protected
Definition at line 216 of file DroneTest.java.
Referenced by workspace.ARDroneNavData.src.controller.DroneTest.getYaw().
The documentation for this class was generated from the following file:
DroneTest.java