Life of 3.14159: Drone.DroneController.Location Class Reference
Drone.DroneController.Location Class Reference
Public Member Functions
Location ()
void centerWorld ()
void updateLocation ()
float getX ()
float getY ()
float getZ ()
Coordinates getXYZvelocities ()
Private Attributes
float currentY
float currentX
float currentZ
long currentT
float currentYvel
float currentXvel
float currentZvel
Static Private Attributes
static final float startX = 0f
static final float startY = 0f
static final float startZ = 0f
Detailed Description
This class represents the drones percieved location of itself, it provides a method to update its position, as well as accessor methods for the X,Y and Z coordinate components.
Author
orpheus
Definition at line 12 of file Location.java.
Constructor & Destructor Documentation
Drone.DroneController.Location.Location ()
preliminary initialisation
Definition at line 38 of file Location.java.
     {
         currentYvel = 0;
         currentXvel = 0;
         currentZvel = 0;
         currentT    = System.currentTimeMillis()*1000;
     }
Member Function Documentation
void Drone.DroneController.Location.centerWorld ()
center the drone on the current point
Definition at line 49 of file Location.java.
References Drone.DroneController.Location.startX, Drone.DroneController.Location.startY, and Drone.DroneController.Location.startZ.
Referenced by Drone.DroneController.DroneController.initialiseDrone().
     {
         currentY = startY;
         currentX = startX;
         currentZ = startZ;
         currentT = System.currentTimeMillis()*1000;
     }
float Drone.DroneController.Location.getX ()
get X value for drone position
Returns
Definition at line 86 of file Location.java.
References Drone.DroneController.Location.currentX.
Referenced by Drone.DroneController.AutoPilot.AdjustXState.adjustAction(), and Drone.DroneController.AutoPilot.ThinkingState.adjustAction().
     {
         return currentX;
     }
Coordinates Drone.DroneController.Location.getXYZvelocities ()
return the x,y and z velocities as a coordinate set, each coord corresponds to its velocity i.e. the x component is the x velocity etc
Returns
Definition at line 114 of file Location.java.
References Drone.Hardware.SensorManager.getXvelocity(), Drone.Hardware.SensorManager.getYvelocity(), and Drone.Hardware.SensorManager.getZvelocity().
     {
         return new Coordinates(SensorManager.getXvelocity(),
                                SensorManager.getYvelocity(),
                                SensorManager.getZvelocity());
     }
float Drone.DroneController.Location.getY ()
retrieve Y value for drone position
Returns
Definition at line 95 of file Location.java.
References Drone.DroneController.Location.currentY.
Referenced by Drone.DroneController.AutoPilot.AdjustYState.adjustAction(), and Drone.DroneController.AutoPilot.ThinkingState.adjustAction().
     {
         return currentY;
     }
float Drone.DroneController.Location.getZ ()
retrieve Z value for drone position
Returns
Definition at line 104 of file Location.java.
References Drone.DroneController.Location.currentZ.
Referenced by Drone.DroneController.AutoPilot.AdjustZState.adjustAction(), and Drone.DroneController.AutoPilot.ThinkingState.adjustAction().
     {
         return currentZ;
     }
void Drone.DroneController.Location.updateLocation ()
update X, Y and Z positions
Definition at line 60 of file Location.java.
References Drone.DroneController.Location.currentT, Drone.DroneController.Location.currentXvel, Drone.DroneController.Location.currentYvel, Drone.DroneController.Location.currentZvel, Drone.Hardware.SensorManager.getXvelocity(), and Drone.Hardware.SensorManager.getYvelocity().
     {
         //set initial values
         float initialYvel = currentYvel;
         float initialXvel = currentXvel;
         float initialZvel = currentZvel;
         long  initialT    = currentT;
         currentYvel = SensorManager.getYvelocity();
         currentXvel = SensorManager.getXvelocity();
         currentZvel = SensorManager.getYvelocity();
         currentT    = System.currentTimeMillis()*1000;
         //use SUVAT formulae
         currentX = currentX +
                 ((initialXvel + currentXvel)*(currentT-initialT)) / 2;
         currentY = currentY +
                 ((initialYvel + currentYvel)*(currentT-initialT)) / 2;
         currentZ = currentZ +
                 ((initialZvel + currentZvel)*(currentT-initialT)) / 2;
     }
Member Data Documentation
long Drone.DroneController.Location.currentT private
Current Time
Definition at line 27 of file Location.java.
Referenced by Drone.DroneController.Location.updateLocation().
float Drone.DroneController.Location.currentX private
Current X position in meters
Definition at line 23 of file Location.java.
Referenced by Drone.DroneController.Location.getX().
float Drone.DroneController.Location.currentXvel private
Current X velocity
Definition at line 31 of file Location.java.
Referenced by Drone.DroneController.Location.updateLocation().
float Drone.DroneController.Location.currentY private
Current Y position in meters
Definition at line 21 of file Location.java.
Referenced by Drone.DroneController.Location.getY().
float Drone.DroneController.Location.currentYvel private
Current Y velocity
Definition at line 29 of file Location.java.
Referenced by Drone.DroneController.Location.updateLocation().
float Drone.DroneController.Location.currentZ private
Current Z position in meters
Definition at line 25 of file Location.java.
Referenced by Drone.DroneController.Location.getZ().
float Drone.DroneController.Location.currentZvel private
Current Z velocity
Definition at line 33 of file Location.java.
Referenced by Drone.DroneController.Location.updateLocation().
final float Drone.DroneController.Location.startX = 0f static private
X zero position constant
Definition at line 15 of file Location.java.
Referenced by Drone.DroneController.Location.centerWorld().
final float Drone.DroneController.Location.startY = 0f static private
Y zero position constant
Definition at line 17 of file Location.java.
Referenced by Drone.DroneController.Location.centerWorld().
final float Drone.DroneController.Location.startZ = 0f static private
Z zero position constant
Definition at line 19 of file Location.java.
Referenced by Drone.DroneController.Location.centerWorld().
The documentation for this class was generated from the following file:
Location.java