Life of 3.14159: Drone.DroneController.AutoPilot.AdjustXState Class Reference
Drone.DroneController.AutoPilot.AdjustXState Class Reference
Public Member Functions
void adjustAction (AutoPilot autopilot)
String toString ()
Detailed Description
The autopilot state in which the drone knows its X coordinate is incorrect.
Author
orpheus
Definition at line 7 of file AdjustXState.java.
Member Function Documentation
void Drone.DroneController.AutoPilot.AdjustXState.adjustAction (AutoPilot autopilot)
Compares the current X to the target X and moves the drone in the appropriate direction.
Exceptions
Exception
check if too far right
check if too far left
Implements Drone.DroneController.AutoPilot.AutoPilotState.
Definition at line 16 of file AdjustXState.java.
References Drone.DroneController.AutoPilot.AutoPilot.ADJUST_INTERVAL, Drone.DroneController.AutoPilot.AutoPilotState.adjustAction(), Drone.DroneController.AutoPilot.AutoPilot.commandManager, Drone.DroneController.AutoPilot.AutoPilot.defaultState, Drone.DroneController.AutoPilot.AutoPilot.ERROR, Drone.DroneController.Location.getX(), Drone.DroneCommands.AT_Command_Manager.left, Drone.DroneController.AutoPilot.AutoPilot.location, Drone.DroneCommands.AT_Command_Manager.right, Drone.DroneController.AutoPilot.AutoPilot.setState(), Drone.DroneController.AutoPilot.AutoPilot.state, and Drone.DroneController.AutoPilot.AutoPilot.xTarget.
     {
         if (autopilot.location.getX() > autopilot.xTarget + AutoPilot.ERROR)
         {
             //move left
             System.out.println("adjust left");
             autopilot.commandManager.left(AutoPilot.ADJUST_INTERVAL);
         }
         if (autopilot.location.getX() < autopilot.xTarget - AutoPilot.ERROR)
         {
             //move right
             System.out.println("adjust right");
             autopilot.commandManager.right(AutoPilot.ADJUST_INTERVAL);
         }
         autopilot.setState(autopilot.defaultState);
         autopilot.state.adjustAction(autopilot);
     }
String Drone.DroneController.AutoPilot.AdjustXState.toString ()
get the string label belonging to the state
Returns
"adjusting X position"
Implements Drone.DroneController.AutoPilot.AutoPilotState.
Definition at line 42 of file AdjustXState.java.
     {
         return "adjusting X position";
     }
The documentation for this class was generated from the following file:
AdjustXState.java