Life of 3.14159: Drone.View.BasicSwingView Class Reference
Drone.View.BasicSwingView Class Reference
Public Member Functions
BasicSwingView (DroneController controller)
void refresh (Location loc)
Private Member Functions
void setupMainWindow ()
void setupInstruments ()
void combineGUIComponents ()
Private Attributes
JFrame window
Guage guages
Detailed Description
Author
orpheus
Definition at line 16 of file BasicSwingView.java.
Constructor & Destructor Documentation
Drone.View.BasicSwingView.BasicSwingView (DroneController controller)
Definition at line 24 of file BasicSwingView.java.
References Drone.View.BasicSwingView.combineGUIComponents(), Drone.View.BasicSwingView.setupInstruments(), and Drone.View.BasicSwingView.setupMainWindow().
     {
         droneController = controller;
         setupMainWindow();
         setupInstruments();
         combineGUIComponents();
     }
Member Function Documentation
void Drone.View.BasicSwingView.combineGUIComponents () private
Definition at line 65 of file BasicSwingView.java.
Referenced by Drone.View.BasicSwingView.BasicSwingView().
     {
         window.setLayout(new GridLayout(2,0));
         window.add(guages);
         window.add(alt);
         window.add(alt2);
         window.setVisible(true);
         window.pack();
     }
void Drone.View.BasicSwingView.refresh (Location loc)
refreshes the view with the provided data
Implements Drone.View.View.
Definition at line 35 of file BasicSwingView.java.
     {
     }
void Drone.View.BasicSwingView.setupInstruments () private
Definition at line 55 of file BasicSwingView.java.
References Drone.View.Guages.Guage.update().
Referenced by Drone.View.BasicSwingView.BasicSwingView().
     {
         guages = new Guage();
         alt = new Guage();
         alt2 = new Guage();
         alt2.update(32f);
         alt.update(85f);
         guages.update(3.1415998732498324f);
 ;   }
void Drone.View.BasicSwingView.setupMainWindow () private
Definition at line 40 of file BasicSwingView.java.
References Drone.DroneController.DroneController.shutdownDrone().
Referenced by Drone.View.BasicSwingView.BasicSwingView().
     {
         window = new JFrame("test");
         window.setSize(450, 800);
         window.addWindowListener(new WindowAdapter()
             {
                 public void windowClosing(WindowEvent windowEvent)
                 {
                     droneController.shutdownDrone();
                     System.exit(0);
                 }
             });
     }
Member Data Documentation
Guage Drone.View.BasicSwingView.guages private
Definition at line 20 of file BasicSwingView.java.
JFrame Drone.View.BasicSwingView.window private
Definition at line 19 of file BasicSwingView.java.
The documentation for this class was generated from the following file:
BasicSwingView.java