Life of 3.14159: Drone.DroneCommands.ATInvoker Class Reference
Drone.DroneCommands.ATInvoker Class Reference
Public Member Functions
ATInvoker ()
void setCommand (ATCommand cmmnd)
void execute () throws Exception
Private Attributes
ATCommand command
int sequenceNum
Detailed Description
This class is the invoker in a GOF Command patter, it holds a reference to a command passedto it as a method argument, and provides the functionality to execute the stored command. This particular implementation also keeps track of the Sequence number of the commands being given, so as to aid in their construction.
Author
orpheus
Definition at line 12 of file ATInvoker.java.
Constructor & Destructor Documentation
Drone.DroneCommands.ATInvoker.ATInvoker ()
Default CTOR, initialise stuff
Definition at line 23 of file ATInvoker.java.
     {
         sequenceNum=1;
     }
Member Function Documentation
void Drone.DroneCommands.ATInvoker.execute () throws Exception
executes the concrete <ATCommand> currently stored in the local reference.
Parameters
sequence
Exceptions
Exception
Definition at line 42 of file ATInvoker.java.
References Drone.DroneCommands.ATCommand.execute(), and Drone.DroneCommands.ATInvoker.sequenceNum.
Referenced by Drone.DroneCommands.AT_Command_Manager.backward(), Drone.DroneCommands.AT_Command_Manager.down(), Drone.DroneCommands.AT_Command_Manager.forward(), Drone.DroneCommands.AT_Command_Manager.hover(), Drone.DroneCommands.AT_Command_Manager.land(), Drone.DroneCommands.AT_Command_Manager.left(), Drone.DroneCommands.AT_Command_Manager.lTurn(), Drone.DroneCommands.AT_Command_Manager.right(), Drone.DroneCommands.AT_Command_Manager.rTurn(), Drone.DroneCommands.AT_Command_Manager.takeOff(), and Drone.DroneCommands.AT_Command_Manager.up().
     {
         command.execute(sequenceNum);
         ++sequenceNum;
         Thread.sleep(40l, 0);
     }
void Drone.DroneCommands.ATInvoker.setCommand (ATCommand cmmnd)
store a concrete command in the local <ATCommand> reference
Parameters
cmmnd the concrete command to be stored
Definition at line 32 of file ATInvoker.java.
Referenced by Drone.DroneCommands.AT_Command_Manager.backward(), Drone.DroneCommands.AT_Command_Manager.down(), Drone.DroneCommands.AT_Command_Manager.forward(), Drone.DroneCommands.AT_Command_Manager.hover(), Drone.DroneCommands.AT_Command_Manager.land(), Drone.DroneCommands.AT_Command_Manager.left(), Drone.DroneCommands.AT_Command_Manager.lTurn(), Drone.DroneCommands.AT_Command_Manager.right(), Drone.DroneCommands.AT_Command_Manager.rTurn(), Drone.DroneCommands.AT_Command_Manager.takeOff(), and Drone.DroneCommands.AT_Command_Manager.up().
     {
         command = cmmnd;
     }
Member Data Documentation
ATCommand Drone.DroneCommands.ATInvoker.command private
reference to a concrete command
Definition at line 15 of file ATInvoker.java.
int Drone.DroneCommands.ATInvoker.sequenceNum private
the number of commands in the sequence
Definition at line 17 of file ATInvoker.java.
Referenced by Drone.DroneCommands.ATInvoker.execute().
The documentation for this class was generated from the following file:
ATInvoker.java