Life of 3.14159: Drone.Helpers.Coordinates Class Reference
Drone.Helpers.Coordinates Class Reference
Public Member Functions
Coordinates ()
Coordinates (float xVal, float yVal, float zVal)
void setCoordinates (float xVal, float yVal, float zVal)
float getX ()
float getY ()
float getZ ()
Detailed Description
this class represents a set of X,Y,Z - Coordinates, it is a convienience object
Author
orpheus
Definition at line 7 of file Coordinates.java.
Constructor & Destructor Documentation
Drone.Helpers.Coordinates.Coordinates ()
default constructor, initialises a coordinates object with origin values
Definition at line 19 of file Coordinates.java.
     {
         x = 0;
         y = 0;
         z = 0;
     }
Drone.Helpers.Coordinates.Coordinates (float xVal, float yVal, float zVal)
initialise a coordinates objext with the provided values
Parameters
xVal
yVal
zVal
Definition at line 32 of file Coordinates.java.
     {
         x = xVal;
         y = yVal;
         z = zVal;
     }
Member Function Documentation
float Drone.Helpers.Coordinates.getX ()
return the x component of the coordinates
Returns
Definition at line 56 of file Coordinates.java.
Referenced by Drone.DroneController.AutoPilot.AutoPilot.moveToTarget().
     {
         return x;
     }
float Drone.Helpers.Coordinates.getY ()
return the y component of the coordinates
Returns
Definition at line 65 of file Coordinates.java.
Referenced by Drone.DroneController.AutoPilot.AutoPilot.moveToTarget().
     {
         return y;
     }
float Drone.Helpers.Coordinates.getZ ()
return the z component of the coordinates
Returns
Definition at line 74 of file Coordinates.java.
Referenced by Drone.DroneController.AutoPilot.AutoPilot.moveToTarget().
     {
         return z;
     }
void Drone.Helpers.Coordinates.setCoordinates (float xVal, float yVal, float zVal)
set the values associated with this coordinates object
Parameters
xVal
yVal
zVal
Definition at line 45 of file Coordinates.java.
     {
         x = xVal;
         y = yVal;
         z = zVal;
     }
The documentation for this class was generated from the following file:
Coordinates.java