Life of 3.14159: Drone.Helpers.IntToFloat Class Reference
Drone.Helpers.IntToFloat Class Reference
Static Public Member Functions
static int input (float f)
Static Private Attributes
static ByteBuffer bb = ByteBuffer.allocate(4)
static FloatBuffer fb = bb.asFloatBuffer()
static IntBuffer ib = bb.asIntBuffer()
Detailed Description
Author
orpheus
Definition at line 11 of file IntToFloat.java.
Member Function Documentation
static int Drone.Helpers.IntToFloat.input (float f) static
Parameters
f
Returns
Definition at line 25 of file IntToFloat.java.
Referenced by Drone.DroneCommands.Cmnd_TurnLeft.execute(), Drone.DroneCommands.Cmnd_TurnRight.execute(), Drone.DroneCommands.Cmnd_MoveForward.execute(), Drone.DroneCommands.Cmnd_MoveUp.execute(), Drone.DroneCommands.Cmnd_MoveRight.execute(), Drone.DroneCommands.Cmnd_MoveDown.execute(), Drone.DroneCommands.Cmnd_MoveBackward.execute(), and Drone.DroneCommands.Cmnd_MoveLeft.execute().
     {
         fb.put(0, f);
         return ib.get(0);
     }
Member Data Documentation
ByteBuffer Drone.Helpers.IntToFloat.bb = ByteBuffer.allocate(4) static private
Definition at line 14 of file IntToFloat.java.
FloatBuffer Drone.Helpers.IntToFloat.fb = bb.asFloatBuffer() static private
Definition at line 16 of file IntToFloat.java.
IntBuffer Drone.Helpers.IntToFloat.ib = bb.asIntBuffer() static private
Definition at line 18 of file IntToFloat.java.
The documentation for this class was generated from the following file:
IntToFloat.java