Life of 3.14159: workspace.ARDroneCaptureImage.src.QRTools Class Reference
workspace.ARDroneCaptureImage.src.QRTools Class Reference
Static Public Member Functions
static void main (String[] args)
static BufferedImage GenerateQRCode (int width, int height, String content) throws Exception
static void GenerateQRCode (int width, int height, String content, String filename, String imageFormat) throws Exception
static String DecodeQRCode (BufferedImage image) throws Exception
static String DecodeQRCode (String filename) throws Exception
Detailed Description
Definition at line 25 of file QRTools.java.
Member Function Documentation
static String workspace.ARDroneCaptureImage.src.QRTools.DecodeQRCode (BufferedImage image) throws Exception static
Definition at line 57 of file QRTools.java.
Referenced by workspace.ARDroneCaptureImage.src.QRTools.DecodeQRCode(), and workspace.ARDroneCaptureImage.src.QRTools.main().
{
         Map<DecodeHintType, Object> whatHints = new EnumMap<DecodeHintType, Object>(
                 DecodeHintType.class);
         whatHints.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
         whatHints.put(DecodeHintType.POSSIBLE_FORMATS,
                 EnumSet.allOf(BarcodeFormat.class));
         whatHints.put(DecodeHintType.PURE_BARCODE, Boolean.FALSE);
         LuminanceSource tmpSource = new BufferedImageLuminanceSource(image);
         BinaryBitmap tmpBitmap = new BinaryBitmap(
                 new HybridBinarizer(tmpSource));
         MultiFormatReader tmpBarcodeReader = new MultiFormatReader();
         com.google.zxing.Result tmpResult;
         String tmpFinalResult = "";
         try {
             if (whatHints != null && !whatHints.isEmpty()) {
                 tmpResult = tmpBarcodeReader.decode(tmpBitmap, whatHints);
             } else {
                 tmpResult = tmpBarcodeReader.decode(tmpBitmap);
             }
             // setting results.
             tmpFinalResult = String.valueOf(tmpResult.getText());
         } catch (Exception tmpExcpt) {
             System.out.println("BarCodeUtil.decode Excpt err - "
                     + tmpExcpt.toString() + " - " + tmpExcpt.getMessage());
         }
         return (tmpFinalResult);
     }
static String workspace.ARDroneCaptureImage.src.QRTools.DecodeQRCode (String filename) throws Exception static
Definition at line 85 of file QRTools.java.
References workspace.ARDroneCaptureImage.src.QRTools.DecodeQRCode().
{
         File whatFile = new File(filename);
         // check the required parameters
         if (whatFile == null || whatFile.getName().trim().isEmpty()) {
             throw new IllegalArgumentException(
                     "File not found, or invalid file name.");
         }
         BufferedImage tmpBfrImage;
         try {
             tmpBfrImage = ImageIO.read(whatFile);
         } catch (IOException tmpIoe) {
             throw new Exception(tmpIoe.getMessage());
         }
         if (tmpBfrImage == null) {
             throw new IllegalArgumentException("Could not decode image.");
         }
         return (DecodeQRCode(tmpBfrImage));
     }
static BufferedImage workspace.ARDroneCaptureImage.src.QRTools.GenerateQRCode (int width, int height, String content) throws Exception static
Definition at line 40 of file QRTools.java.
{
         BitMatrix bitMatrix = new QRCodeWriter().encode(content,
                 BarcodeFormat.QR_CODE, width, height);
         return (MatrixToImageWriter.toBufferedImage(bitMatrix));
     }
static void workspace.ARDroneCaptureImage.src.QRTools.GenerateQRCode (int width, int height, String content, String filename, String imageFormat) throws Exception static
Definition at line 47 of file QRTools.java.
{
         File tmpFile = new File(filename);
         BitMatrix bitMatrix = new QRCodeWriter().encode(content,
                 BarcodeFormat.QR_CODE, width, height);
         BufferedOutputStream outputStream = new BufferedOutputStream(
                 new FileOutputStream(tmpFile));
         MatrixToImageWriter.writeToStream(bitMatrix, imageFormat, outputStream);
     }
static void workspace.ARDroneCaptureImage.src.QRTools.main (String[] args) static
Definition at line 26 of file QRTools.java.
References workspace.ARDroneCaptureImage.src.QRTools.DecodeQRCode().
{
         try {
             // GenerateQRCode(500,500,"LEFT","j:\\drone\\left.png","png");
             // GenerateQRCode(500,500,"RIGHT","j:\\drone\\right.png","png");
             // GenerateQRCode(500,500,"QUIT","j:\\drone\\quit.png","png");
             String tmpRetString = DecodeQRCode("c:\\temp\\qr.bmp");
             System.out.println(tmpRetString);
         } catch (Exception tmpExpt) {
             System.out.println("main: " + "Excpt err! (" + tmpExpt.getMessage()
                     + ")");
         }
         System.out.println("main: " + "Program end.");
     }
The documentation for this class was generated from the following file:
QRTools.java