Life of 3.14159: Drone.Hardware.ATReciever Class Reference
Drone.Hardware.ATReciever Class Reference
Public Member Functions
ATReciever (InetAddress inetaddr, DatagramSocket atSock)
void send_at_cmd (String at_cmd) throws Exception
Private Attributes
InetAddress inet_addr
DatagramSocket atSocket
Detailed Description
This class is the interaction between the hardware and the software, it is where individual concrete commands get executed.
Author
orpheus
Definition at line 12 of file ATReciever.java.
Constructor & Destructor Documentation
Drone.Hardware.ATReciever.ATReciever (InetAddress inetaddr, DatagramSocket atSock)
initialise the InetAddress and the DatagramSocket
Definition at line 22 of file ATReciever.java.
     {
         inet_addr = inetaddr;
         atSocket = atSock;
     }
Member Function Documentation
void Drone.Hardware.ATReciever.send_at_cmd (String at_cmd) throws Exception
Sends the actual AT-Command passed to it as a string argument.
Parameters
at_cmd the AT_Command
Exceptions
Exception ???
Definition at line 33 of file ATReciever.java.
Referenced by Drone.DroneCommands.Cmnd_TakeOff.execute(), Drone.DroneCommands.Cmnd_AutoLand.execute(), Drone.DroneCommands.Cmnd_Hover.execute(), Drone.DroneCommands.Cmnd_TurnRight.execute(), Drone.DroneCommands.Cmnd_TurnLeft.execute(), Drone.DroneCommands.Cmnd_MoveDown.execute(), Drone.DroneCommands.Cmnd_MoveRight.execute(), Drone.DroneCommands.Cmnd_MoveLeft.execute(), Drone.DroneCommands.Cmnd_MoveForward.execute(), Drone.DroneCommands.Cmnd_MoveUp.execute(), Drone.DroneCommands.Cmnd_MoveBackward.execute(), and DroneBasics.main().
     {
 //      System.out.println("AT command: " + at_cmd);
         byte[] buffer = (at_cmd + "\r").getBytes();
         DatagramPacket packet = new DatagramPacket(buffer, buffer.length,
                 inet_addr, 5556);
         atSocket.send(packet);
     }
Member Data Documentation
DatagramSocket Drone.Hardware.ATReciever.atSocket private
The socket to send AT commands to
Definition at line 17 of file ATReciever.java.
InetAddress Drone.Hardware.ATReciever.inet_addr private
The IP address of the drone
Definition at line 15 of file ATReciever.java.
The documentation for this class was generated from the following file:
ATReciever.java