Life of 3.14159: Drone.DroneCommands.AT_Command_Manager Class Reference
Drone.DroneCommands.AT_Command_Manager Class Reference
Public Member Functions
AT_Command_Manager ()
void takeOff ()
void land ()
void forward (int time)
void backward (int time)
void lTurn (int time)
void rTurn (int time)
void left (int time)
void right (int time)
void up (int time)
void down (int time)
void hover (int time)
Private Member Functions
void initSockets ()
Private Attributes
ATInvoker invoker
ATCommand takeOff
ATCommand land
ATCommand forward
ATCommand back
ATCommand lTurn
ATCommand rTurn
ATCommand right
ATCommand left
ATCommand up
ATCommand down
ATCommand hover
DatagramSocket commandSocket
DatagramSocket navSocket
InetAddress ipAddress
long t
Detailed Description
The client of the ATCommand pattern, also the facade through which users give the drone instructions.
Author
orpheus
Definition at line 11 of file AT_Command_Manager.java.
Constructor & Destructor Documentation
Drone.DroneCommands.AT_Command_Manager.AT_Command_Manager ()
initialise stuff
Exceptions
Exception
Definition at line 50 of file AT_Command_Manager.java.
References Drone.DroneCommands.AT_Command_Manager.initSockets().
     {
         initSockets();
         invoker = new ATInvoker();
         takeOff = new Cmnd_TakeOff(ipAddress,commandSocket);
         land = new Cmnd_AutoLand(ipAddress,commandSocket);
         forward = new Cmnd_MoveLeft(ipAddress,commandSocket);
         back = new Cmnd_MoveForward(ipAddress,commandSocket);
         lTurn = new Cmnd_TurnLeft(ipAddress,commandSocket);
         rTurn = new Cmnd_TurnRight(ipAddress,commandSocket);
         right = new Cmnd_MoveRight(ipAddress,commandSocket);
         left = new Cmnd_MoveBackward(ipAddress,commandSocket);
         up = new Cmnd_MoveUp(ipAddress,commandSocket);
         down = new Cmnd_MoveDown(ipAddress,commandSocket);
         hover = new Cmnd_Hover(ipAddress,commandSocket);
     }
Member Function Documentation
void Drone.DroneCommands.AT_Command_Manager.backward (int time)
make the drone go back
Parameters
time
Exceptions
Exception
Definition at line 108 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
Referenced by Drone.DroneController.AutoPilot.AdjustYState.adjustAction().
     {
         invoker.setCommand(back);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.down (int time)
make the drone decrease altitude
Parameters
time
Exceptions
Exception
Definition at line 198 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(down);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.forward (int time)
make the drone go forward
Parameters
time
Exceptions
Exception
Definition at line 93 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(forward);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.hover (int time)
make the drone decrease altitude
Parameters
time
Exceptions
Exception
Definition at line 213 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(this.hover);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.initSockets () private
initialise the sockets for communication
Exceptions
Exception
Definition at line 228 of file AT_Command_Manager.java.
Referenced by Drone.DroneCommands.AT_Command_Manager.AT_Command_Manager().
     {
         try{
         byte[] ip_bytes = new byte[4];
         ip_bytes[0] = (byte)192;
         ip_bytes[1] = (byte)168;
         ip_bytes[2] = (byte)1;
         ip_bytes[3] = (byte)1;
         //create an InetAddress from the byte array above
         ipAddress = InetAddress.getByAddress(ip_bytes);
         //create sockets and set timeout value
         commandSocket = new DatagramSocket();
         navSocket = new DatagramSocket();
         commandSocket.setSoTimeout(3000);
         navSocket.setSoTimeout(3000);
         }
         catch(Exception e)
         {
             System.out.println("--sockets error in command manager--");
         }
     }
void Drone.DroneCommands.AT_Command_Manager.land ()
make the drone land
Exceptions
Exception
Definition at line 82 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(land);
         invoker.execute();
     }
void Drone.DroneCommands.AT_Command_Manager.left (int time)
make the drone strafe left
Parameters
time
Exceptions
Exception
Definition at line 153 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(left);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.lTurn (int time)
make the drone turn left
Parameters
time
Exceptions
Exception
Definition at line 123 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(lTurn);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.right (int time)
make the drone strafe right
Parameters
time
Exceptions
Exception
Definition at line 168 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(right);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.rTurn (int time)
make the drone turn right
Parameters
time
Exceptions
Exception
Definition at line 138 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(rTurn);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
void Drone.DroneCommands.AT_Command_Manager.takeOff ()
make the drone take off
Exceptions
Exception
Definition at line 73 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(takeOff);
         invoker.execute();
     }
void Drone.DroneCommands.AT_Command_Manager.up (int time)
make the drone increase altitude
Parameters
time
Exceptions
Exception
Definition at line 183 of file AT_Command_Manager.java.
References Drone.DroneCommands.ATInvoker.execute(), and Drone.DroneCommands.ATInvoker.setCommand().
     {
         invoker.setCommand(up);
         t = System.currentTimeMillis();
         while (System.currentTimeMillis()< t + time)
         {
             invoker.execute();
         }
     }
Member Data Documentation
ATCommand Drone.DroneCommands.AT_Command_Manager.back private
the "backwards" command
Definition at line 22 of file AT_Command_Manager.java.
DatagramSocket Drone.DroneCommands.AT_Command_Manager.commandSocket private
the socket to send the AT_Commands to
Definition at line 38 of file AT_Command_Manager.java.
ATCommand Drone.DroneCommands.AT_Command_Manager.down private
the "descend" command
Definition at line 34 of file AT_Command_Manager.java.
Referenced by Drone.DroneController.AutoPilot.AdjustZState.adjustAction(), and DroneBasics.main().
ATCommand Drone.DroneCommands.AT_Command_Manager.forward private
the "forwards" command
Definition at line 20 of file AT_Command_Manager.java.
Referenced by Drone.DroneController.AutoPilot.AdjustYState.adjustAction(), and DroneBasics.main().
ATCommand Drone.DroneCommands.AT_Command_Manager.hover private
the "hover" command
Definition at line 36 of file AT_Command_Manager.java.
Referenced by DroneBasics.main().
ATInvoker Drone.DroneCommands.AT_Command_Manager.invoker private
Reference to an Invoker object, will hold the commands to be executed
Definition at line 14 of file AT_Command_Manager.java.
InetAddress Drone.DroneCommands.AT_Command_Manager.ipAddress private
the IP address of the done
Definition at line 42 of file AT_Command_Manager.java.
ATCommand Drone.DroneCommands.AT_Command_Manager.land private
the "land"
Definition at line 18 of file AT_Command_Manager.java.
Referenced by Drone.DroneController.DroneController.land(), and DroneBasics.main().
ATCommand Drone.DroneCommands.AT_Command_Manager.left private
the "strafe left" command
Definition at line 30 of file AT_Command_Manager.java.
Referenced by Drone.DroneController.AutoPilot.AdjustXState.adjustAction(), and DroneBasics.main().
ATCommand Drone.DroneCommands.AT_Command_Manager.lTurn private
the "left turn" command
Definition at line 24 of file AT_Command_Manager.java.
DatagramSocket Drone.DroneCommands.AT_Command_Manager.navSocket private
the socket to get the NavData from
Definition at line 40 of file AT_Command_Manager.java.
ATCommand Drone.DroneCommands.AT_Command_Manager.right private
the "strafe right" command
Definition at line 28 of file AT_Command_Manager.java.
Referenced by Drone.DroneController.AutoPilot.AdjustXState.adjustAction(), and DroneBasics.main().
ATCommand Drone.DroneCommands.AT_Command_Manager.rTurn private
the "right turn" command
Definition at line 26 of file AT_Command_Manager.java.
long Drone.DroneCommands.AT_Command_Manager.t private
holder for the current time
Definition at line 44 of file AT_Command_Manager.java.
ATCommand Drone.DroneCommands.AT_Command_Manager.takeOff private
the "take-off" command
Definition at line 16 of file AT_Command_Manager.java.
Referenced by DroneBasics.main().
ATCommand Drone.DroneCommands.AT_Command_Manager.up private
the "ascend" command
Definition at line 32 of file AT_Command_Manager.java.
Referenced by Drone.DroneController.AutoPilot.AdjustZState.adjustAction(), and DroneBasics.main().
The documentation for this class was generated from the following file:
AT_Command_Manager.java