Life of 3.14159: Drone.DroneController.AutoPilot.AutoPilot Class Reference
Drone.DroneController.AutoPilot.AutoPilot Class Reference
Public Member Functions
AutoPilot (Location loc, AT_Command_Manager cm)
void moveToTarget (Coordinates target) throws Exception
Protected Member Functions
void setState (AutoPilotState aState)
Protected Attributes
Location location
AT_Command_Manager commandManager
AutoPilotState state
AutoPilotState defaultState
float xTarget
float yTarget
float zTarget
Static Protected Attributes
static final float ERROR = 0.1f
static final int ADJUST_INTERVAL = 50
Detailed Description
The context class for the autopilot state pattern implementation, provides users with the ability to move the drone to a set of coordinates using anobject of thistype.
Author
orpheus
Definition at line 16 of file AutoPilot.java.
Constructor & Destructor Documentation
Drone.DroneController.AutoPilot.AutoPilot.AutoPilot (Location loc, AT_Command_Manager cm)
create an autopilot given a Lovation and an AT_Command_Manager
Parameters
loc the Location object
cm the CommandManager
Definition at line 41 of file AutoPilot.java.
     {
         location = loc;
         state = null;
         commandManager = cm;
         defaultState = new ThinkingState();
     }
Member Function Documentation
void Drone.DroneController.AutoPilot.AutoPilot.moveToTarget (Coordinates target) throws Exception
Move the drone toward a target set of Cioordinates.
Parameters
target Coordinates object containing the X,Y,Z, components
Exceptions
Exception
Definition at line 54 of file AutoPilot.java.
References Drone.DroneController.AutoPilot.AutoPilotState.adjustAction(), and Drone.DroneController.AutoPilot.AutoPilot.setState().
Referenced by Drone.DroneController.DroneController.main().
     {
         xTarget = target.getX();
         yTarget = target.getY();
         zTarget = target.getZ();
         setState(defaultState);
         System.out.println("<<AUTOPILOT ENGAGED>>");
         state.adjustAction(this);
     }
void Drone.DroneController.AutoPilot.AutoPilot.setState (AutoPilotState aState) protected
set the state to the provided AutoPilotState
Parameters
aState
Definition at line 68 of file AutoPilot.java.
Referenced by Drone.DroneController.AutoPilot.AutoPilot.moveToTarget().
     {
         state = aState;
     }
Member Data Documentation
final int Drone.DroneController.AutoPilot.AutoPilot.ADJUST_INTERVAL = 50 static protected
the amount of time, by which each adjustement is carried out
Definition at line 21 of file AutoPilot.java.
Referenced by Drone.DroneController.AutoPilot.AdjustXState.adjustAction(), Drone.DroneController.AutoPilot.AdjustZState.adjustAction(), and Drone.DroneController.AutoPilot.AdjustYState.adjustAction().
AT_Command_Manager Drone.DroneController.AutoPilot.AutoPilot.commandManager protected
reference to the command manager
Definition at line 25 of file AutoPilot.java.
AutoPilotState Drone.DroneController.AutoPilot.AutoPilot.defaultState protected
Definition at line 28 of file AutoPilot.java.
final float Drone.DroneController.AutoPilot.AutoPilot.ERROR = 0.1f static protected
value for Error in measurements
Definition at line 19 of file AutoPilot.java.
Referenced by Drone.DroneController.AutoPilot.AdjustXState.adjustAction(), Drone.DroneController.AutoPilot.AdjustZState.adjustAction(), and Drone.DroneController.AutoPilot.AdjustYState.adjustAction().
Location Drone.DroneController.AutoPilot.AutoPilot.location protected
reference to the drones location object
Definition at line 23 of file AutoPilot.java.
AutoPilotState Drone.DroneController.AutoPilot.AutoPilot.state protected
internal reference to state object
Definition at line 27 of file AutoPilot.java.
float Drone.DroneController.AutoPilot.AutoPilot.xTarget protected
target X-coord
Definition at line 30 of file AutoPilot.java.
float Drone.DroneController.AutoPilot.AutoPilot.yTarget protected
target Y-coord
Definition at line 32 of file AutoPilot.java.
float Drone.DroneController.AutoPilot.AutoPilot.zTarget protected
target Z-coord
Definition at line 34 of file AutoPilot.java.
The documentation for this class was generated from the following file:
AutoPilot.java