Life of 3.14159: Drone.DroneController.DroneController Class Reference
Drone.DroneController.DroneController Class Reference
Public Member Functions
void run ()
void shutdownDrone ()
void initialiseDrone ()
Private Member Functions
void land ()
Private Attributes
View view
SensorManager sensorManager
AT_Command_Manager commandManager
Location world
AutoPilot autopilot
Static Private Attributes
static final float LANDED_DIST = 0.1f
Detailed Description
Author
orpheus
Definition at line 15 of file DroneController.java.
Member Function Documentation
void Drone.DroneController.DroneController.initialiseDrone ()
Definition at line 52 of file DroneController.java.
References Drone.DroneController.Location.centerWorld().
Referenced by Drone.DroneController.DroneController.run().
     {
         System.out.println("<<INITIALISING DRONE>> ");
         System.out.println("<Graphical Interface> ");
         view = new BasicSwingView(this);
         System.out.println("<Sensors> ");
         sensorManager = new SensorManager();
         System.out.println("<Controls> ");
         commandManager = new AT_Command_Manager();
         System.out.println("<World> ");
         world = new Location();
         System.out.println("<Orienting> ");
         world.centerWorld();
         System.out.println("<AutoPilot> ");
         autopilot = new AutoPilot(world, commandManager);
         System.out.println("<<DRONE READY>>");
     }
void Drone.DroneController.DroneController.land () private
Definition at line 70 of file DroneController.java.
References Drone.Hardware.SensorManager.getAltitude(), Drone.DroneCommands.AT_Command_Manager.land, and Drone.DroneController.DroneController.LANDED_DIST.
Referenced by Drone.DroneController.DroneController.shutdownDrone().
     {
         do
         {commandManager.land();}
         while(SensorManager.getAltitude() > LANDED_DIST );
     }
void Drone.DroneController.DroneController.run ()
Definition at line 27 of file DroneController.java.
References Drone.DroneController.DroneController.initialiseDrone().
Referenced by Drone.Drone.main().
     {
         initialiseDrone();
 //      Coordinates target = new Coordinates(1.0f,1.0f,1.0f);
 //      autopilot.moveToTarget(target);
     }
void Drone.DroneController.DroneController.shutdownDrone ()
Definition at line 37 of file DroneController.java.
References Drone.DroneController.DroneController.land().
Referenced by Drone.View.BasicSwingView.setupMainWindow().
     {
         System.out.println("<<SHUTTING DOWN DRONE>>");
         System.out.println("<attempting to land>");
         land();
         System.out.println("<kill: autopilot>");
         autopilot = null;
         System.out.println("<kill: world>");
         world = null;
         System.out.println("<kill: sensors>");
         sensorManager = null;
         System.out.println("<kill: controls>");
         commandManager = null;
     }
Member Data Documentation
AutoPilot Drone.DroneController.DroneController.autopilot private
Definition at line 21 of file DroneController.java.
AT_Command_Manager Drone.DroneController.DroneController.commandManager private
Definition at line 19 of file DroneController.java.
final float Drone.DroneController.DroneController.LANDED_DIST = 0.1f static private
Definition at line 22 of file DroneController.java.
Referenced by Drone.DroneController.DroneController.land().
SensorManager Drone.DroneController.DroneController.sensorManager private
Definition at line 18 of file DroneController.java.
View Drone.DroneController.DroneController.view private
Definition at line 17 of file DroneController.java.
Location Drone.DroneController.DroneController.world private
Definition at line 20 of file DroneController.java.
The documentation for this class was generated from the following file:
DroneController.java