Life of 3.14159: Drone.Hardware.SensorManager Class Reference
Drone.Hardware.SensorManager Class Reference
Public Member Functions
SensorManager ()
SensorManager getInstance ()
Public Member Functions inherited from workspace.ARDroneNavData.src.NavData
Mode getMode ()
int getSequence ()
boolean isControlReceived ()
FlyingState getFlyingState ()
Static Public Member Functions
static float getXvelocity ()
static float getYvelocity ()
static float getZvelocity ()
static float getYaw ()
static float getPitch ()
static float getRoll ()
static float getAltitude ()
static List< VisionTag > getVisionTags ()
Static Public Member Functions inherited from workspace.ARDroneNavData.src.NavData
static void main (String args[])
static float getAltitude ()
static int getBattery ()
static ControlAlgorithm getControlAlgorithm ()
static CtrlState getControlState ()
static float getLongitude ()
static float getPitch ()
static float getRoll ()
static float getVx ()
static float getVz ()
static float getYaw ()
static boolean isAcquisitionThreadOn ()
static boolean isADCWatchdogDelayed ()
static boolean isAltitudeControlActive ()
static boolean isAngelsOutOufRange ()
static boolean isATCodedThreadOn ()
static boolean isBatteryTooHigh ()
static boolean isBatteryTooLow ()
static boolean isCommunicationProblemOccurred ()
static boolean isControlWatchdogDelayed ()
static boolean isCutoutSystemDetected ()
static boolean isEmergency ()
static boolean isFlying ()
static boolean isGyrometersDown ()
static boolean isMotorsDown ()
static boolean isNavDataBootstrap ()
static boolean isNavDataDemoOnly ()
static boolean isNavDataThreadOn ()
static boolean isNotEnoughPower ()
static boolean isPICVersionNumberOK ()
static boolean isTimerElapsed ()
static boolean isTooMuchWind ()
static boolean isTrimReceived ()
static boolean isTrimRunning ()
static boolean isTrimSucceeded ()
static boolean isUltrasonicSensorDeaf ()
static boolean isUserFeedbackOn ()
static boolean isVideoEnabled ()
static boolean isVideoThreadOn ()
static boolean isVisionEnabled ()
static List< VisionTag > getVisionTags ()
static void setVisionTags (List< VisionTag > vt)
static void createFromData (ByteBuffer buf, int len)
static void send_at_cmd (String at_cmd) throws Exception
Private Attributes
NavData navData
Additional Inherited Members
Static Protected Attributes inherited from workspace.ARDroneNavData.src.NavData
static Mode mode
static boolean flying
static boolean videoEnabled
static boolean visionEnabled
static ControlAlgorithm controlAlgorithm
static boolean altitudeControlActive
static boolean userFeedbackOn
static boolean controlReceived
static boolean trimReceived
static boolean trimRunning
static boolean trimSucceeded
static boolean navDataDemoOnly
static boolean navDataBootstrap
static boolean motorsDown
static boolean gyrometersDown
static boolean batteryTooLow
static boolean batteryTooHigh
static boolean timerElapsed
static boolean notEnoughPower
static boolean angelsOutOufRange
static boolean tooMuchWind
static boolean ultrasonicSensorDeaf
static boolean cutoutSystemDetected
static boolean PICVersionNumberOK
static boolean ATCodedThreadOn
static boolean navDataThreadOn
static boolean videoThreadOn
static boolean acquisitionThreadOn
static boolean controlWatchdogDelayed
static boolean ADCWatchdogDelayed
static boolean communicationProblemOccurred
static boolean emergency
static int sequence
static CtrlState ctrl_state
static int battery
static float altitude
static float pitch
static float roll
static float yaw
static float vx
static float vy
static float vz
static List< VisionTag > vision_tags
Detailed Description
This is the class to use if you wish to get raw data from the sensors
Author
orpheus
Definition at line 13 of file SensorManager.java.
Constructor & Destructor Documentation
Drone.Hardware.SensorManager.SensorManager ()
initialise the sensor manager
Exceptions
Exception
Definition at line 25 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.main().
     {
         navData = new NavData();
         String[] args = {""};
         NavData.main(args);
     }
Member Function Documentation
static float Drone.Hardware.SensorManager.getAltitude () static
Retrieve the Altitude
Returns
Altitude
Definition at line 90 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getAltitude().
Referenced by Drone.DroneController.DroneController.land().
     {
         return NavData.getAltitude();
     }
SensorManager Drone.Hardware.SensorManager.getInstance ()
Definition at line 104 of file SensorManager.java.
     {
         return this;
     }
static float Drone.Hardware.SensorManager.getPitch () static
Retrieve the pitch value
Returns
pitch value
Definition at line 72 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getPitch().
     {
         return NavData.getPitch();
     }
static float Drone.Hardware.SensorManager.getRoll () static
retrieve the roll value
Returns
roll value
Definition at line 81 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getRoll().
     {
         return NavData.getRoll();
     }
static List<VisionTag> Drone.Hardware.SensorManager.getVisionTags () static
Retrieve a list of the vision tage
Returns
List<VisionTag>
Definition at line 99 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getVisionTags().
     {
         return NavData.getVisionTags();
     }
static float Drone.Hardware.SensorManager.getXvelocity () static
retrieve the X velocity
Returns
X velocity
Definition at line 36 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getVx().
Referenced by Drone.DroneController.Location.getXYZvelocities(), and Drone.DroneController.Location.updateLocation().
     {
         return NavData.getVx();
     }
static float Drone.Hardware.SensorManager.getYaw () static
Retrieve the Yaw value
Returns
Yaw value
Definition at line 63 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getYaw().
     {
         return NavData.getYaw();
     }
static float Drone.Hardware.SensorManager.getYvelocity () static
retrieve the Y velocity
Returns
Y velocity
Definition at line 45 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getLongitude().
Referenced by Drone.DroneController.Location.getXYZvelocities(), and Drone.DroneController.Location.updateLocation().
     {
         //getLongitude() actually returns NavData.Vy
         return NavData.getLongitude();
     }
static float Drone.Hardware.SensorManager.getZvelocity () static
retrieve the Z velocity
Returns
Z velocity
Definition at line 54 of file SensorManager.java.
References workspace.ARDroneNavData.src.NavData.getVz().
Referenced by Drone.DroneController.Location.getXYZvelocities().
     {
         return NavData.getVz();
     }
Member Data Documentation
NavData Drone.Hardware.SensorManager.navData private
A reference to a NavData object, strip down NavData.java to bare essentials
Definition at line 19 of file SensorManager.java.
The documentation for this class was generated from the following file:
SensorManager.java