Life of 3.14159: workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType Enum Reference
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType Enum Reference
Values for the detection type on drone cameras.
Public Member Functions
int getValue ()
Static Public Member Functions
static VisionTagType fromInt (int v)
Public Attributes
CAD_TYPE_HORIZONTL =(0)
CAD_TYPE_VERTICAL =(1)
CAD_TYPE_VISION =(2)
CAD_TYPE_NONE =(3)
CAD_TYPE_COCARDE =(4)
CAD_TYPE_ORIENTED_COCARDE =(5)
CAD_TYPE_STRIPE =(6)
CAD_TYPE_H_COCARDE =(7)
CAD_TYPE_H_ORIENTED_COCARDE =(8)
CAD_TYPE_STRIPE_V =(9)
CAD_TYPE_MULTIPLE_DETECTION_MODE =(10)
CAD_TYPE_NUM =(11)
Private Member Functions
VisionTagType (int value)
Private Attributes
int value
Detailed Description
Values for the detection type on drone cameras.
Definition at line 17 of file VisionTag.java.
Constructor & Destructor Documentation
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.VisionTagType (int value) private
Definition at line 45 of file VisionTag.java.
{
             this.value = value;
         }
Member Function Documentation
static VisionTagType workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt (int v) static
Definition at line 53 of file VisionTag.java.
References workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_COCARDE, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_H_COCARDE, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_H_ORIENTED_COCARDE, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_HORIZONTL, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_MULTIPLE_DETECTION_MODE, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_NONE, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_NUM, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_ORIENTED_COCARDE, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_STRIPE, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_STRIPE_V, workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_VERTICAL, and workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_VISION.
Referenced by workspace.ARDroneNavData.src.NavData.parseVisionTags(), and workspace.ARDroneNavData.src.controller.DroneTest.parseVisionTags().
{
             switch (v) {
             case 0:
                 return VisionTagType.CAD_TYPE_HORIZONTL;
             case 1:
                 return VisionTagType.CAD_TYPE_VERTICAL;
             case 2:
                 return VisionTagType.CAD_TYPE_VISION;
             case 3:
                 return VisionTagType.CAD_TYPE_NONE;
             case 4:
                 return VisionTagType.CAD_TYPE_COCARDE;
             case 5:
                 return VisionTagType.CAD_TYPE_ORIENTED_COCARDE;
             case 6:
                 return VisionTagType.CAD_TYPE_STRIPE;
             case 7:
                 return VisionTagType.CAD_TYPE_H_COCARDE;
             case 8:
                 return VisionTagType.CAD_TYPE_H_ORIENTED_COCARDE;
             case 9:
                 return VisionTagType.CAD_TYPE_STRIPE_V;
             case 10:
                 return VisionTagType.CAD_TYPE_MULTIPLE_DETECTION_MODE;
             case 11:
                 return VisionTagType.CAD_TYPE_NUM;
             default:
                 System.out.println("Invalid vision tag type " + v);
                 System.exit(1);
                 return VisionTagType.CAD_TYPE_HORIZONTL;
             }
         }
int workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.getValue ()
Definition at line 49 of file VisionTag.java.
{
             return value;
         }
Member Data Documentation
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_COCARDE =(4)
Definition at line 22 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_H_COCARDE =(7)
Definition at line 28 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_H_ORIENTED_COCARDE =(8)
Definition at line 29 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_HORIZONTL =(0)
Definition at line 18 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_MULTIPLE_DETECTION_MODE =(10)
Definition at line 33 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_NONE =(3)
Definition at line 21 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_NUM =(11)
Definition at line 41 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_ORIENTED_COCARDE =(5)
Definition at line 23 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_STRIPE =(6)
Definition at line 27 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_STRIPE_V =(9)
Definition at line 33 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_VERTICAL =(1)
Definition at line 19 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.CAD_TYPE_VISION =(2)
Definition at line 20 of file VisionTag.java.
Referenced by workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.fromInt().
int workspace.ARDroneNavData.src.controller.VisionTag.VisionTagType.value private
Definition at line 43 of file VisionTag.java.
The documentation for this enum was generated from the following file:
VisionTag.java