Life of 3.14159: workspace.ARDroneNavData.src.controller.NavDataTag Enum Reference
workspace.ARDroneNavData.src.controller.NavDataTag Enum Reference
Public Member Functions
int getValue ()
Public Attributes
NAVDATA_DEMO_TAG =(0)
NAVDATA_TIME_TAG =(1)
NAVDATA_RAW_MEASURES_TAG =(2)
NAVDATA_PHYS_MEASURES_TAG =(3)
NAVDATA_GYROS_OFFSETS_TAG
NAVDATA_EULER_ANGLES_TAG =(5)
NAVDATA_REFERENCES_TAG =(6)
NAVDATA_TRIMS_TAG =(7)
NAVDATA_RC_REFERENCES_TAG
NAVDATA_PWM_TAG =(9)
NAVDATA_ALTITUDE_TAG =(10)
NAVDATA_VISION_RAW_TAG =(11)
NAVDATA_VISION_OF_TAG =(12)
NAVDATA_VISION_TAG
NAVDATA_VISION_PERF_TAG =(14)
NAVDATA_TRACKERS_SEND_TAG =(15)
NAVDATA_VISION_DETECT_TAG =(16)
NAVDATA_WATCHDOG_TAG
NAVDATA_ADC_DATA_FRAME_TAG =(18)
NAVDATA_VIDEO_STREAM_TAG =(19)
NAVDATA_CKS_TAG =(0xFFFF)
Private Member Functions
NavDataTag (int value)
Private Attributes
int value
Detailed Description
Definition at line 2 of file NavDataTag.java.
Constructor & Destructor Documentation
workspace.ARDroneNavData.src.controller.NavDataTag.NavDataTag (int value) private
Definition at line 12 of file NavDataTag.java.
     {
         this.value = value;
     }
Member Function Documentation
int workspace.ARDroneNavData.src.controller.NavDataTag.getValue ()
Definition at line 17 of file NavDataTag.java.
     {
         return value;
     }
Member Data Documentation
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_ADC_DATA_FRAME_TAG =(18)
Definition at line 8 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_ALTITUDE_TAG =(10)
Definition at line 6 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_CKS_TAG =(0xFFFF)
Definition at line 8 of file NavDataTag.java.
Referenced by workspace.ARDroneNavData.src.NavData.createFromData(), and workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_DEMO_TAG =(0)
Definition at line 4 of file NavDataTag.java.
Referenced by workspace.ARDroneNavData.src.NavData.createFromData(), and workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_EULER_ANGLES_TAG =(5)
Definition at line 5 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_GYROS_OFFSETS_TAG
Initial value:
=(
            4)
Definition at line 4 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_PHYS_MEASURES_TAG =(3)
Definition at line 4 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_PWM_TAG =(9)
Definition at line 6 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_RAW_MEASURES_TAG =(2)
Definition at line 4 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_RC_REFERENCES_TAG
Initial value:
=(
            8)
Definition at line 5 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_REFERENCES_TAG =(6)
Definition at line 5 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_TIME_TAG =(1)
Definition at line 4 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_TRACKERS_SEND_TAG =(15)
Definition at line 7 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_TRIMS_TAG =(7)
Definition at line 5 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_VIDEO_STREAM_TAG =(19)
Definition at line 8 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_VISION_DETECT_TAG =(16)
Definition at line 7 of file NavDataTag.java.
Referenced by workspace.ARDroneNavData.src.NavData.createFromData(), and workspace.ARDroneNavData.src.controller.DroneTest.createFromData().
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_VISION_OF_TAG =(12)
Definition at line 6 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_VISION_PERF_TAG =(14)
Definition at line 7 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_VISION_RAW_TAG =(11)
Definition at line 6 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_VISION_TAG
Initial value:
=(
            13)
Definition at line 6 of file NavDataTag.java.
workspace.ARDroneNavData.src.controller.NavDataTag.NAVDATA_WATCHDOG_TAG
Initial value:
=(
            17)
Definition at line 7 of file NavDataTag.java.
int workspace.ARDroneNavData.src.controller.NavDataTag.value private
Definition at line 10 of file NavDataTag.java.
The documentation for this enum was generated from the following file:
NavDataTag.java