Life of 3.14159: Drone.DroneController.AutoPilot.AutoPilotState Interface Reference
Drone.DroneController.AutoPilot.AutoPilotState Interface Reference
Public Member Functions
void adjustAction (AutoPilot autopilot)
String toString ()
Detailed Description
template for autopilot states
Author
orpheus
Definition at line 7 of file AutoPilotState.java.
Member Function Documentation
void Drone.DroneController.AutoPilot.AutoPilotState.adjustAction (AutoPilot autopilot)
perform appropriate XYZ adjustement
Exceptions
Exception
Implemented in Drone.DroneController.AutoPilot.ThinkingState, Drone.DroneController.AutoPilot.AdjustXState, Drone.DroneController.AutoPilot.AdjustYState, and Drone.DroneController.AutoPilot.AdjustZState.
Referenced by Drone.DroneController.AutoPilot.AdjustXState.adjustAction(), Drone.DroneController.AutoPilot.AdjustYState.adjustAction(), Drone.DroneController.AutoPilot.AdjustZState.adjustAction(), Drone.DroneController.AutoPilot.ThinkingState.adjustAction(), and Drone.DroneController.AutoPilot.AutoPilot.moveToTarget().
String Drone.DroneController.AutoPilot.AutoPilotState.toString ()
get a string label belonging to the state
Returns
string containing the state label
Implemented in Drone.DroneController.AutoPilot.ThinkingState, Drone.DroneController.AutoPilot.AdjustXState, Drone.DroneController.AutoPilot.AdjustYState, and Drone.DroneController.AutoPilot.AdjustZState.
The documentation for this interface was generated from the following file:
AutoPilotState.java